"""Add Workout schedule model

Revision ID: ccd79e1d321b
Revises: 2603791c9bc4
Create Date: 2025-01-05 07:48:56.178530

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccd79e1d321b'
down_revision = '2603791c9bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('workout', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('workout_owner_id_fkey', 'workout', type_='foreignkey')
    op.create_foreign_key(None, 'workout', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.create_foreign_key('workout_owner_id_fkey', 'workout', 'user', ['owner_id'], ['id'])
    op.alter_column('workout', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workout', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workout', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
